language: node_js
node_js:
- '6.1'
before_script:
- python -m SimpleHTTPServer &
- sleep 2
addons:
  sauce_connect: true
env:
  global:
  - secure: kjRWntwkOTA02N/OgQmhH2qikjmNU0DPwjmTsXtw3Q/FjDRtFi/FxdSA8h7R9y9rfwG3FajA/Z6i0XVmHyzuoUZcIW3nl9u8IBkkaIaIb3JMQVsDaaopnUqOHguAvTEdtdFXTA8j2qAiQ+uA73r5WUqB1z1hlIK2UD/GlASzVUF4+L95E1E5SaFzLnUqtOp1hDUsknXbfZkYXQrIO4/uFEbXLViRA5E5LPW9go8xOYhZmGzFHebJlMF37dH6HkLHGZxSiJj4Qr89W+HEf+nvBgbRo33K1PQE97XN46Tk3Vgp3kCASLFODNLP9K+JnMWvEAg1MECMoq8PU5oEsq4+TfMbcoCZDiEjdh5AiuiuRnHY6VYB38+kbYRbY1AzPb2O3taN7AqUt72QgzqWb/pVL+G7YgAIzfmWHTW8HU0D6c0CihpekpKKBavYjnyurP94hTER3t+/U768qsvC6elPL35ieMGPCbMaIRvzpUOAdr47udL4ss5Z5USphe/TL9j2UCRWZ3+lkvXkPgfebeTSzJ74qDjpWe3sytFK7mcf3+2D/iZQ0Ax7Pvdwz/ghjem7onSySyMCl/+Oa0VLYgOqSEnHWWDktBrSPDgvtXRxnKIPyjGnU0NFMUtp538o399S9r2rgdXeh9YcTRJeQjM4AxpZOYwdoBk9SHQ5V6HOd0U=
  - secure: IanyGQnWNHoTZ6vBvS4kr9dB0b6SBTyM0TxJkf+JD10/6QvFrDCdS9d5xHxnOV0eWSna2bu3DK9HT9MCjsG5EpmjpCwSMOP/u4bZ58mTgkRp9naax1PYqsBpTyvK+PVDbIyEWMFIhJNwIR3qMdojQYN/SA4aqdVw84CQmei2ooku4Wiwj/SPwzrvv7vVjaXqhDO1MH5faQLDEs0piwnVl4oimmndOqhkOOt/BAyWfjPYwtoQ3ILvWq1baYspV0+5yq1hHnypyId4viEp6AHDDy2yOwnD2TwtM/aKg18vD+qVv4wCLQarv2w0isrqIOjlJKQKadJemjYcHTpqkjAO4a7BCvYy4gK6vTQUOLk5Kh0Htv57vRQQBkaHbU/lv3nXLmmU02SfZTWcUHS6m7JB4vp4XMof5D//XedlFq1f9jo9QgWD71Leo/cIr2/RsmgXxfbBCgzURIYnhxso5Jv8D/PXF9uzG9UFFzxTV08aK0TdDwWSdKRDcssN4FmGBwMXTWxxRExl7ZiVdO5U1RJ6qPqtVY8sHEF5mxSyhV0QgGtu3dZm/4mM2ajM9MvTIOYbOWf+7GvTSkxbKX3E6TPIRcWB3Z648ZNWOUEfrZoyHKivBrm4KZckfOQWyPPDuaXdrR84rvkuyRdSAI4Q7I2Ztgy6K9ZeWS3yzgeD183FiwE=
