language: node_js
node_js:
- '6.1'
before_script:
- python -m SimpleHTTPServer &
- sleep 2
addons:
  sauce_connect: true
env:
  global:
  - secure: hqtZvxnwaoWftjrIfHK/Y5W9guktBw2n9ryVSzkkxIVdKmeCYaGsoU3gYfdplUBDQ45HDyrDNN/uYoruHTi7GIj1IJ5SDIxdeOmI4+obwg0D7pENYYXiSaknBiJBpu6czy2XgoFJyBEhp8ELCeoDjKoCOANXDo7Dy/wmhrkZNRczSY55cD0txZU2RSdowpJmzJ5FCeS1nnDNX8pDeEVu6sK17P3WyQN8jUyidSfLlj0BdcywuhcqkKb7DETsJ4XtRfsHZb74TvZ2lDTKRT7WPbih5B5qs6EdXuu2QajUKns7gSGHCltqB6fxkeYO6IRao6cZ0GUlNAeqvgPW7wZaqjklMrIq3S63gIkr0Bt+Fo0YS1qZ645EI5Fa3cOZvZwIgAYDrZhz3IgPSfMdcvssxibZYrNM394AyytgaetVyr1eEXCUGkOkJzfL+OAVj6MdMeJqGeM9EffR843wHlhbFHPKRNgtfGTacZUBpM+yvw5RL53rwj9NErpllDrEMg0vwxjSO7wAMRdoexqpJTFOxN3nR896Q7H5cVfK06QgqpY0ExEUtACEwB5CEtG3Eu1LamiigI2sG9DO8q4r8+2bTb+vH6KDttsIf5N1nTXu1hGVk+o9iB54+KSJ1fGAMjGHSj7TNjbE2M9oPR36LnukNsI+bdIOnJ+07IVhlMD4Jwg=
  - secure: QccMM7USAB1Lr+DOnEnlNXA+PEaqTWVU1Xk9XlewSjs0ITUxOvJ1WDov9LdIeyZKoxprFvDRO3lAQYcuMsOwVu9M/ijU80uaM/XAGQAxTSqgOzOa/bJ26FboQGq1tmVcgyQCoG8riSg1zHF0N/2J41qLynbbJ/UqN/kgafPSfqWWymUX8sSmVVXFeTYct8UPVnIg8qgqb0XsdO04DFBIiSu7NLYDfsEWov4zb9eDpO996h1nmNzIqbvJ8LA7T62c+rcjCY1NxtMvHlPVMr607p7Ij8yFXHVfVQuR/uq+oK5c3udUSfgtwzFa7Xg3tWfsR7QT6IaNPTIDWXr5yHzSAj2wy6PRdFjs013ICKUMJWXqmrlIhV7uRh7ZMw0zs0IG9nqdn6VhChZjvMo4cBH/beA/mHigCkaAqmxlpes8mTImcu2LT5wQIIajgL+qdDdRG7B4qIiBoVKuARbICrxPFpi+xnGnAJZI8HzAegIgf8x6/N60HuNtxpI/gA/l1eidNUQlCneZXguObR0SX7EnJqLdgPGrYjSKxM72D+6DIrZHQbmTodbYo5U4vYTa7IgFHsmtyC+PlNJny7cU1UXtLRlqGuBUHVqaofKeEs5Wzl19g0fYXPaoU6PJL6GEl7BKnFLfiYzCCTTuF2446h5kOmSKA5tqvDnI5vrFYznUS8w=
